### PR TITLE
feat: JMeter Scripts to run the performance test against EDC

### LINKED ISSUE #285: MXD Performance Test - Prepare JMeter Scripts to run the performance test against EDC
### Description

- Create Jmeter Script.
- Create a shell script to run the performance test.

### PR DESCRIPTION
**Pull request by ciprian-nicuta**
## Description

Added JMeter Scripts to run the performance test against EDC.
Created a shell script to run the performance test which can be used later as a entry point for a container.

Closes #285

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ciprian-nicuta** [comment]
Hi @ndr-brt, can you please take a look here?

**Comment by ndr-brt** [comment]
@ciprian-nicuta TBH I don't have an up-to-date expert knowledge about JMeter (or, better, it has been a while... :D ), so it would require me to getting some confidence before, and it could take some time maybe @paullatzelsperger or @wolf4ood are in a better shape

**Comment by paullatzelsperger** [comment]
@ciprian-nicuta @ndr-brt unfortunately my JMeter days are long in the past as well :/

**Review by ndr-brt — COMMENTED** [review]
I mean we could also go with merging, I can tell that there's nothing malicious here, but no valuable feedback about the content

**Comment by wolf4ood** [comment]
I also don't have strong skills on Jmeter but as @ndr-brt  was saying probably we can go on and merge this?

Probably i would only add some description  which outline the tests plan or what the scripts  actually do?

**Comment by ciprian-nicuta** [comment]
> I also don't have strong skills on Jmeter but as @ndr-brt was saying probably we can go on and merge this?
> 
> Probably i would only add some description which outline the tests plan or what the scripts actually do?

@wolf4ood 

The script documentation was already elaborated but provided in a separate [PR](https://github.com/eclipse-tractusx/tutorial-resources/pull/296). Please check [User Guide](https://github.com/eclipse-tractusx/tutorial-resources/pull/296/files#diff-92d4f06ea54d49030aa8015d109b04305e41bc1041a85332afc8fb107e49b79eR115) section of added readme file for more detailed information about the scripts. Now, just to have an integrated view of the documentation and the code, the branch containing documentation was merged in here.

Beside the mentioned documentation, also a shell script [mxd/performance-tests/experiment_controller.sh ](https://github.com/eclipse-tractusx/tutorial-resources/pull/296/files#diff-3499a6aafe4361470b37de62278b648d6c277bf459bde57027840151eca619b4) wrapping the JMeter calls was now also merged into this PR. It provides users with ability to run JMeter tests in a very simplified manner and does not require JMeter app installation, taking care of the following:

1. Environment Setup

- Creates infrastructure resources defined in Terraform
- Deploys Prometheus
- Creates performance-tests-pod using [run_experiment.sh](https://github.com/eclipse-tractusx/tutorial-resources/pull/292/files#diff-0a01c9f9fff3d1135bc5dc0c14a03082efa88d01b25a618f34261c1e226780f0) as entry point.

2. Cleans up the environment after the tests are executed
3. Provides the tests results in easy to use archives.

**Review by wolf4ood — APPROVED** [review]

**Review by ndr-brt — APPROVED** [review]

**Pull request merged**
