### PR TITLE
fix: Generate private / public key pair for transfer proxy

### LINKED ISSUE #231: Transfer fails
### Current Behavior

Transfer doesn't complete.

### Expected Behavior

Transfer should be completed successfully.

### Steps To Reproduce

- Initiate negotiation.
- Validate Negotiation state `FINALIZED`.
- Initiate transfer.
- Check Transfer State.

Related to: eclipse-edc/Connector#3810

### Possible Fix
- Generate a private / public key pair and store it in connector's vault.
- Define vault keys as connector config. Check config details [here](https://github.com/eclipse-edc/Connector/tree/main/extensions/control-plane/transfer/transfer-data-plane).

### PR DESCRIPTION
**Pull request by hemantxpatel**
## Description

- Generate private / public key pair.
- Store it in connector's vault.
- Define configs `edc.transfer.proxy.token.signer.privatekey.alias` / `edc.transfer.proxy.token.verifier.publickey.alias`

Closes #231 
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by oliverbusch** [comment]
I've tested the fix, but with this fix it looks like that the created token has an **invalid signature**
image

**Comment by hemantxpatel** [comment]
Hi @oliverbusch, I tested with both `RSA` and `ED25519` key pair.
 It says `Invalid Signature` for both. Even I tried to decode a `vp` token generated via MIW which also says `Invalid Signature` on jwt.io. I don't know what could be the reason.
Screenshot 2024-02-08 205505
Screenshot 2024-02-08 215511

But I was able to fetch data with both type of tokens.
Screenshot 2024-02-08 215550

A sample curl which I am trying to fetch the data.
```shell
curl --location 'http://localhost/alice/api/public' \
--header 'Authorization: eyJraWQiOiJ0cmFuc2ZlclByb3h5VG9rZW5TaWduZXJQdWJsaWNLZXkiLCJhbGciOiJFZERTQSJ9.eyJleHAiOjE3MDc0MDk5NjksImRhZCI6IkdNRU9mQ3pKSmh0bHRPS1MvTDd2Yk9vWCs0dFBsaUVwOTJESmJ2UnZtVityTHE2cWVPaEN0YTFiWHg1aEdVSW1mNG9hTnJ6bktmZFZ5R0NXbDJyNkExU0NhenZWSGRpbjFIN1NuZ0xwODFZUEV2ZkhRRm9PMkp6THdvNEV5K1JPNlNmRlVjZVNOTjJ2aUVDK1ViQnFUS1pPZXJadnB4TWp4RHRuRnZOcUFyRE1mTFl3TG5sQVk1MWFKRWlZMGdqYmxWSHVaR0JHY2djamZSWDc3azd6cnpEM1hmVkcyYVdHbjBMYjdkUjZGSGpLb2FFRlJEQnUvT1lqaGRoVVpaOUwwVHJXdHhuQnBkNjRiQ0duYldYaU1ITDZUTXVnV3poRlBobHVzM0VtbGdCQk9UcmtBNWtwWmN3cTFsSUNtb2x0dGVGY1cwak1meVFhMm9SSE9XdE1RY0d0bGZrK0tsc2VMSzE0dHE3anlqNmpYU2Joditsbnh1T2ptWjhHK1dyYXlpUklkQjFlR0tZPSJ9.OrgooxkfNP5BNU2_rb0ynJn6FJ5znQPgq_ZSY0veGd9ZGkc4pR-V52k6KrgUUdYwHjVV6Uo_hdS_f2dF8zfSBA' \
--header 'X-Api-Key: password' \
--data ''
```

**Comment by oliverbusch** [comment]
@hemantxpatel 
You've fetched the data from alice http://localhost/alice/api/public. What happens if you fetch the data from bob http://localhost/bob/api/public. 

If I do it with alice it works fine. 
With bob it doesn't work. 
And a fetch with an id http://localhost/alice/api/public/1 gets no results.

**Comment by oliverbusch** [comment]
Hi @hemantxpatel , I may be wrong. But my understanding has always been that the consumer backend service never communicates directly with the provider dataplane and that communication always goes through the consumer dataplane. This is how it looks in the EDC sample [transfer-02-consumer-pull](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-02-consumer-pull) and in the consumer pull sequence diagram [transfer-data-plane-consumer-pull](https://github.com/eclipse-edc/Connector/blob/main/docs/developer/diagrams/transfer-data-plane-consumer-pull.png).
In the sample the request comes from **29291** (consumer)
`curl --location --request GET 'http://localhost:29291/public/' --header 'Authorization: <auth code>'`

And this is consistent with the sequence diagram. 

image

Did I make a mistake here?

Regarding http://localhost/alice/api/public/1  not working, i will create a new discussion.

**Comment by hemantxpatel** [comment]
Hi @oliverbusch , in step no 7, you can see consumer backend service communicates to provider data plane.

**Comment by anschl** [comment]
Hi everyone! When can I expect this PR to be merged?

**Review by ndr-brt — APPROVED** [review]

**Pull request merged**
