### PR TITLE
feat: Separate Postgres server for each components

### LINKED ISSUE #226: Deploy Postgres Instance for each components (connectors / miw / keycloak)
### Description

Right now all components share same Postgres instance, which becomes a bottleneck in case of slight increase in traffic to MXD setup.

### Acceptance Criteria

- [ ] Connectors / MIW / Keycloak should have their own Postgres Instance.

### PR DESCRIPTION
**Pull request by hemantxpatel**
## Description

- A new Postgres Terraform Module
- Separate instance for Alice, Bob connectors, MIW and Keycloak.

Closes #226 
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by ndr-brt — COMMENTED** [review]
wouldn't this make the whole environment a lot heavier to spin up?
In the issue #226 you are talking about bottlenecks, but running 4 instances is definitely more expensive that to have 4 database in a single instance, giving that everything runs on a single machine.

**Comment by hemantxpatel** [comment]
@ndr-brt We discovered database exceptions while doing performance tests with the current setup. A single postgres instance was not able to handle multiple connections from alice connector, bob connector, keycloak and MIW simultaneously.
When we deployed separate instances for all 4 components, performance test worked fine.

So, this new setup will require more CPU / memory on the host machine, but it will be more reliable while running performance tests. Otherwise we need to maintain separate branch for performance testing.

**Comment by ndr-brt** [comment]
> @ndr-brt We discovered database exceptions while doing performance tests with the current setup. A single postgres instance was not able to handle multiple connections from alice connector, bob connector, keycloak and MIW simultaneously. When we deployed separate instances for all 4 components, performance test worked fine.
> 
> So, this new setup will require more CPU / memory on the host machine, but it will be more reliable while running performance tests. Otherwise we need to maintain separate branch for performance testing.

that makes me think: is the MXD the right place where to execute the performance tests? because I think its goal should be to provide a simple local T-X dataspace for users to try it out, but dividing everything into separate services will likely make everything heavier to run, and that could lead to frustration

**Comment by hemantxpatel** [comment]
Hi @ndr-brt , I agree system is going to be heavy and host system needs additional resources.

Regarding performance test, we execute it against MXD and all the performance test scripts and including some changes in MXD resides in a branch in our fork. Only problem is maintaining two separate branch is quite hard.

For now  I have tweaked my changes based on a flag (`terraform variable`). Default behaviour is to deploy a common postgres but if needed (while running performance test), multiple instances can be deployed.

Please have a look and share your thought.

**Review by ndr-brt — APPROVED** [review]
looks good to me

**Pull request merged**
